# Generated by Django 5.2.8 on 2025-12-03 09:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamaGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('monthly_contribution_amount', models.DecimalField(decimal_places=2, help_text='Expected monthly contribution per member in KES', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chama Group',
                'verbose_name_plural': 'Chama Groups',
                'db_table': 'chama_groups',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name of the member', max_length=255)),
                ('phone_number', models.CharField(help_text='Kenyan phone number for M-Pesa transactions', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Kenyan phone number (e.g., +254712345678 or 0712345678)', regex='^\\+?254\\d{9}$|^0\\d{9}$')])),
                ('role', models.CharField(choices=[('TREASURER', 'Treasurer'), ('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', help_text='Chama role/permission level', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', help_text='Current membership status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chama Member',
                'verbose_name_plural': 'Chama Members',
                'db_table': 'chama_members',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount in KES', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of transaction')),
                ('transaction_type', models.CharField(choices=[('CONTRIBUTION', 'Contribution'), ('FINE', 'Fine'), ('PAYOUT', 'Payout'), ('EXPENSE', 'Group Expense')], help_text='Type of transaction', max_length=20)),
                ('mpesa_code', models.CharField(help_text='M-Pesa transaction code (unique identifier)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid M-Pesa code (10 alphanumeric characters)', regex='^[A-Z0-9]{10}$')])),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Verification status', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the transaction was verified', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this transaction (typically Treasurer)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, help_text='Member associated with this transaction (not required for group expenses)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='chamas.member')),
                ('verified_by', models.ForeignKey(blank=True, help_text='User who verified this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'chama_transactions',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['phone_number'], name='chama_membe_phone_n_1d860c_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['status'], name='chama_membe_status_9f190b_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['role'], name='chama_membe_role_54ad9d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['mpesa_code'], name='chama_trans_mpesa_c_58902f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'status'], name='chama_trans_transac_d2615b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='chama_trans_date_318f68_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['member', 'date'], name='chama_trans_member__aff2f3_idx'),
        ),
    ]
