"""
Django settings for ChamaNexus project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see:
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see:
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import re
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv
from datetime import datetime

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ============================================================================
# Security Settings
# ============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-development-key-change-this')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes')

# Configure allowed hosts
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,0.0.0.0').split(',')

# Add Render's external hostname if set
RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Add frontend URL if available
FRONTEND_URL = os.getenv('FRONTEND_URL', 'https://chamanexus.onrender.com')
if FRONTEND_URL and FRONTEND_URL not in ALLOWED_HOSTS:
    # Extract domain from URL
    from urllib.parse import urlparse
    parsed = urlparse(FRONTEND_URL)
    if parsed.netloc and parsed.netloc not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(parsed.netloc)

# ============================================================================
# Application Definition
# ============================================================================

INSTALLED_APPS = [
    # Django built-in apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    
    # Local apps
    'accounts',
    'chamas',
    #'dashboard',
    # 'members',   # Uncomment when created
]

# ============================================================================
# Middleware Configuration
# ============================================================================

MIDDLEWARE = [
    # CORS middleware must be at the top
    'corsheaders.middleware.CorsMiddleware',
    
    # Django security middleware
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    
    # Session and authentication middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # Keep this
    
    # Custom CSRF exempt middleware
    'config.middleware.CsrfExemptApiMiddleware',
    
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ============================================================================
# URL Configuration
# ============================================================================

ROOT_URLCONF = 'config.urls'

# ============================================================================
# Template Configuration
# ============================================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ============================================================================
# WSGI Configuration
# ============================================================================

WSGI_APPLICATION = 'config.wsgi.application'

# ============================================================================
# Database Configuration - SIMPLIFIED FOR RENDER
# ============================================================================

# Default to SQLite for development
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Use Render's PostgreSQL database if DATABASE_URL is available
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    # Parse the database URL
    db_config = dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
        conn_health_checks=True,
        ssl_require=True
    )
    
    # Ensure PostgreSQL engine
    db_config['ENGINE'] = 'django.db.backends.postgresql'
    
    # Ensure SSL is required for Render
    if 'OPTIONS' not in db_config:
        db_config['OPTIONS'] = {}
    db_config['OPTIONS']['sslmode'] = 'require'
    
    # Apply the configuration
    DATABASES['default'] = db_config
    
    print("✅ Using PostgreSQL database from Render")
    print(f"📊 Database: {db_config.get('NAME')}")
    print(f"🌐 Host: {db_config.get('HOST')}")
    print(f"🔐 SSL Mode: {db_config.get('OPTIONS', {}).get('sslmode', 'not set')}")
else:
    print("⚠️ Using SQLite database (no DATABASE_URL found)")

# ============================================================================
# Password Validation
# ============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Password hashing (using Argon2 - more secure than default)
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# ============================================================================
# Internationalization
# ============================================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ============================================================================
# Static Files Configuration
# ============================================================================

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# WhiteNoise configuration for serving static files in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ============================================================================
# Default Primary Key Field Type
# ============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# Authentication Settings
# ============================================================================

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Login/Logout URLs (for Django admin if needed)
LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = '/admin/login/'
LOGIN_URL = '/admin/login/'

# ============================================================================
# Django REST Framework Configuration
# ============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Changed to AllowAny for API access
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '1000/hour',
        'user': '10000/hour'
    }
}

# ============================================================================
# CORS Configuration (Fixed for Frontend)
# ============================================================================

# Get allowed origins from environment
CORS_ALLOWED_ORIGINS_ENV = os.getenv(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000,http://127.0.0.1:3000'
).split(',')

CORS_ALLOWED_ORIGINS = [origin.strip() for origin in CORS_ALLOWED_ORIGINS_ENV if origin.strip()]

# Add frontend URL if not already present
if FRONTEND_URL and FRONTEND_URL not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append(FRONTEND_URL)

# Add backend URL for internal calls
BACKEND_URL = f'https://{RENDER_EXTERNAL_HOSTNAME}' if RENDER_EXTERNAL_HOSTNAME else 'https://chamanexus-backend.onrender.com'
if BACKEND_URL and BACKEND_URL not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append(BACKEND_URL)

# Additional CORS settings
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only allow all in DEBUG mode

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'access-control-allow-origin',
]

# ============================================================================
# CSRF Configuration (Fixed for Frontend)
# ============================================================================

# Get CSRF trusted origins from environment
CSRF_TRUSTED_ORIGINS_ENV = os.getenv(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000,http://127.0.0.1:3000'
).split(',')

CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in CSRF_TRUSTED_ORIGINS_ENV if origin.strip()]

# Add frontend and backend URLs
if FRONTEND_URL and FRONTEND_URL not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(FRONTEND_URL)

if BACKEND_URL and BACKEND_URL not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(BACKEND_URL)

# Session settings for authentication
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = not DEBUG  # Secure cookies in production
SESSION_COOKIE_NAME = 'chamanexus_session'

# CSRF settings
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to access for API calls
CSRF_COOKIE_SECURE = not DEBUG  # Secure cookies in production
CSRF_COOKIE_NAME = 'chamanexus_csrf'
CSRF_USE_SESSIONS = False  # Use cookies instead of sessions for CSRF

# API endpoints that should be CSRF exempt (for token auth)
API_CSRF_EXEMPT_PATTERNS = [
    # Root-level routes (frontend expects these)
    r'^/accounts/auth/register/$',
    r'^/accounts/auth/login/$',
    r'^/accounts/auth/logout/$',
    r'^/accounts/password-reset/.*$',
    
    # API v1 routes
    r'^/api/v1/accounts/auth/register/$',
    r'^/api/v1/accounts/auth/login/$',
    r'^/api/v1/accounts/auth/logout/$',
    r'^/api/v1/accounts/password-reset/.*$',
    
    # CSRF token endpoints
    r'^/csrf-token/$',
    r'^/api/v1/csrf-token/$',
    
    # Health check endpoints
    r'^/health/$',
    r'^/api/v1/health/$',
]

# ============================================================================
# Security Headers (Production Only)
# ============================================================================

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

# ============================================================================
# Email Configuration
# ============================================================================

EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND', 
    'django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@chamanexus.com')

# ============================================================================
# Logging Configuration
# ============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'api': {
            'format': '{asctime} - {name} - {levelname} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs/django.log',
            'formatter': 'verbose',
        },
        'api_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs/api.log',
            'formatter': 'api',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'accounts': {
            'handlers': ['console', 'api_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# ============================================================================
# Gunicorn Configuration
# ============================================================================

# Timeout for Gunicorn workers (in seconds)
GUNICORN_TIMEOUT = 120

# Maximum requests a worker will process before restarting
GUNICORN_MAX_REQUESTS = 1000

# Maximum jitter to add to max_requests
GUNICORN_MAX_REQUESTS_JITTER = 50

# Worker class
GUNICORN_WORKER_CLASS = 'sync'

# Number of workers
GUNICORN_WORKERS = 2

# Keep-alive
GUNICORN_KEEPALIVE = 5


# ============================================================================
# Custom Settings
# ============================================================================

# API Configuration
API_VERSION = 'v1'
API_BASE_URL = f'/api/{API_VERSION}'

# Create logs directory if it doesn't exist
(BASE_DIR / 'logs').mkdir(exist_ok=True)
